### ISSUE TITLE
medical use prohibited & GPLv3

### ISSUE THREAD

**Issue by nno** [fahrenfort/ADAM#131]
Greetings,

on http://www.fahrenfort.com/ADAM.htm one can download the toolbox after filling out a form. It says "Using the toolbox for medical purposes is prohibited." 

I did not fill out the form, but found the toolbox here on GitHub (https://github.com/fahrenfort/ADAM/). The license distributed with the toolbox is GPLv3 (LICENSE.txt in the root directory), so I assume that is the applicable license. 

The issue is that prohibiting medical use seems to be an additional term, which if I read the GPLv3 (see section 7 and 10) correctly, could be removed by recipients: "If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term" 

That would make the prohibition rather pointless; I suggest you consider removing the prohibition altogether. If you are concerned about being sued, please note that the GPLv3 license already covers liability (section 16). If you are concerned about the software being used for medical purposes, please consider to include a notice such as done with AFNI (distributed under GPLv2+), see https://afni.nimh.nih.gov/pub/dist/src/README.copyright: 

*** This software was designed to be used only for research purposes. ***
*** Clinical applications are not recommended, and this software has  ***
*** NOT been evaluated by the United States FDA for any clinical use. ***

The crucial difference here is recommendation versus prohibition.

**Comment by fahrenfort** [comment]
Good point Nikolaas,

I will remove the prohibition and replace it with a note of caution expressing that I am not liable for any mistakes in the code and that one should refer to the GPLv3 for details.
Thanks,

Johannes

-----------------------------------------------------------------------------
Johannes Fahrenfort, Assistant Prof at University of Amsterdam | VU Amsterdam
Nieuwe Achtergracht 129B  | room G0.08 | 1001NK | Amsterdam | the Netherlands
Van der Boechorststraat 7 | room B563  | 1081BT | Amsterdam | the Netherlands
web: www.fahrenfort.com <http://www.fahrenfort.com/>   | lab: www.consciousbrainlab.com <http://www.consciousbrainlab.com/>  | t: +31641282406
-----------------------------------------------------------------------------

**Comment by nno** [comment]
Hi Johannes,

excellent, thanks!

best,
Nick
