### ISSUE TITLE
Limit time window for analysis

### ISSUE THREAD

**Issue by ChristineBlume** [fahrenfort/ADAM#143]
One more suggestion for **enhancement**: it would be perfect if it was possible to limit the time window to be included in the first-level analyses. Often, epochs are longer than the time windows of interest.

**Comment by fahrenfort** [comment]
This can be done for group analyses, inspect the help file of adam_compute_group_MVPA and look for the cfg.timelim parameter. Alternatively, simply re-epoch your trials to a smaller time window.
