### ISSUE TITLE
Multiplot limited to 12 plots per figure

### ISSUE THREAD

**Issue by ChristineBlume** [fahrenfort/ADAM#146]
When plotting temporal generalisation matrices, line 221 in adam_plot_MVPA seems to limit the number of plots to 12. This _only_ happens when a plot order is specified, although when plotting temporal generalisation matrices, the line_colors argument does not seem relevant.

**Comment by fahrenfort** [comment]
True. Do you want to plot more than 12 temporal generalization matrices in a single figure? Seems excessive ;-) but I’ll update the code to allow that if you want...

**Comment by ChristineBlume** [comment]
Thanks so much. I am working in sleep research and we have 5 sleep stages, so you always end up with an excessive 5x5 matrix ;-). 
For now, I have adapted the code myself to circumvent the error message (and anyway will have to build a figure from individual plots eventually). If you have time and it's not a major thing, I think it could be helpful though. Thanks a ton!

**Comment by fahrenfort** [comment]
Ah OK! I have updated the code so that this restriction does not count for temporal generalization matrices. I haven’t checked yet whether it works properly, but feel free to try, download from here: Download ZIP <https://github.com/fahrenfort/ADAM/archive/refs/heads/master.zip>

**Comment by ChristineBlume** [comment]
It works! :) Thanks a ton!
