### ISSUE TITLE
Problem with 128-channel Biosemi system (ABC radial layout)

### ISSUE THREAD

**Issue by RenzoLanfranco** [fahrenfort/ADAM#158]
Hi! Thanks for this wonderful toolbox. I have encountered an issue but I'm not sure whether it's an ADAM issue or a FieldTrip issue. In our lab, we use a 128-channel EEG system (Biosemi ActiveTwo) that has an ABC-radial layout (not the 10-20 layout!), and its channel labels are A1-A32, B1-B32, C1-C32, and D1-D32. Unfortunately, ADAM only recognises 8 of these channels (A1 A2 B1 B2 C1 C2 D1 D2). For this reason, I created a bundle in ADAM's select_channels script (I tried to attach the script here but GitHub doesn't let me). These are the relevant new lines:

`bundlenames.BIOSEMI_128_ABC = {'A1' 'A2' 'A3' 'A4' 'A5' 'A6' 'A7' 'A8' 'A9' 'A10' 'A11' 'A12' 'A13' 'A14' 'A15' 'A16' 'A17' 'A18' 'A19' 'A20' 'A21' 'A22' 'A23' 'A24' 'A25' ...
    'A26' 'A27' 'A28' 'A29' 'A30' 'A31' 'A32' 'B1' 'B2' 'B3' 'B4' 'B5' 'B6' 'B7' 'B8' 'B9' 'B10' 'B11' 'B12' 'B13' 'B14' 'B15' 'B16' 'B17' 'B18' 'B19' 'B20' 'B21' 'B22' 'B23' 'B24' 'B25' ...
    'B26' 'B27' 'B28' 'B29' 'B30' 'B31' 'B32' 'C1' 'C2' 'C3' 'C4' 'C5' 'C6' 'C7' 'C8' 'C9' 'C10' 'C11' 'C12' 'C13' 'C14' 'C15' 'C16' 'C17' 'C18' 'C19' 'C20' 'C21' 'C22' 'C23' 'C24' 'C25' ...
    'C26' 'C27' 'C28' 'C29' 'C30' 'C31' 'C32' 'D1' 'D2' 'D3' 'D4' 'D5' 'D6' 'D7' 'D8' 'D9' 'D10' 'D11' 'D12' 'D13' 'D14' 'D15' 'D16' 'D17' 'D18' 'D19' 'D20' 'D21' 'D22' 'D23' 'D24' 'D25' ...
    'D26' 'D27' 'D28' 'D29' 'D30' 'D31' 'D32'}; % 128-channel Biosemi ABC system`

I also created a channel location file - it's already contained in the EEG datasets, but I added it just in case (I also tried to attach this BESA file but GitHub doesn't let me):

`% These are the EEG and EOG channels according to the radial ABC definition:
if exist('biosemi_128_ABC_chanlocdata','file')
    load('biosemi_128_ABC_chanlocdata');
else
    chanlocdata = readlocs(trycapfile,'importmode','native'); % from ABC 128-electrode biosemi system
end`

Unfortunately, it didn't work. ADAM recognises that there are 128 channels, but it only selects those 8 channels I mentioned above (screenshot attached). Thanks so much for the help!

Renzo
![ADAM_channelselectionerror](https://user-images.githubusercontent.com/40778736/199520411-ac238259-6506-4bec-9452-36ee2f61a257.png)

**Comment by fahrenfort** [comment]
Hi Renzo, I cannot replicate this problem using the files your provided me, so I'm closing the issue...
